# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/todo.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/todo.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x10proto/todo.proto\"f\n\x04Todo\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x1c\n\x06status\x18\x03 \x01(\x0e\x32\x0c.Todo.Status\"#\n\x06Status\x12\x0c\n\x08\x43OMPLETE\x10\x00\x12\x0b\n\x07PENDING\x10\x01\"\x1f\n\x08\x41llTodos\x12\x13\n\x04todo\x18\x01 \x03(\x0b\x32\x05.Todo\"\x07\n\x05\x45mpty2\xe4\x01\n\x07TodoApp\x12\x1a\n\x07\x41\x64\x64Todo\x12\x05.Todo\x1a\x06.Empty\"\x00\x12#\n\x0cListAllTodos\x12\x06.Empty\x1a\t.AllTodos\"\x00\x12\x1b\n\x08\x45\x64itTodo\x12\x05.Todo\x1a\x06.Empty\"\x00\x12\x1c\n\nRemoveTodo\x12\x05.Todo\x1a\x05.Todo\"\x00\x12\x1e\n\x0cUpdateStatus\x12\x05.Todo\x1a\x05.Todo\"\x00\x12\"\n\rListAllStream\x12\x06.Empty\x1a\x05.Todo\"\x00\x30\x01\x12\x19\n\x07GetTodo\x12\x05.Todo\x1a\x05.Todo\"\x00\x62\x06proto3'
)



_TODO_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='Todo.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='COMPLETE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PENDING', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=87,
  serialized_end=122,
)
_sym_db.RegisterEnumDescriptor(_TODO_STATUS)


_TODO = _descriptor.Descriptor(
  name='Todo',
  full_name='Todo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Todo.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='Todo.content', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='Todo.status', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TODO_STATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=122,
)


_ALLTODOS = _descriptor.Descriptor(
  name='AllTodos',
  full_name='AllTodos',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='todo', full_name='AllTodos.todo', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=155,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=157,
  serialized_end=164,
)

_TODO.fields_by_name['status'].enum_type = _TODO_STATUS
_TODO_STATUS.containing_type = _TODO
_ALLTODOS.fields_by_name['todo'].message_type = _TODO
DESCRIPTOR.message_types_by_name['Todo'] = _TODO
DESCRIPTOR.message_types_by_name['AllTodos'] = _ALLTODOS
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Todo = _reflection.GeneratedProtocolMessageType('Todo', (_message.Message,), {
  'DESCRIPTOR' : _TODO,
  '__module__' : 'proto.todo_pb2'
  # @@protoc_insertion_point(class_scope:Todo)
  })
_sym_db.RegisterMessage(Todo)

AllTodos = _reflection.GeneratedProtocolMessageType('AllTodos', (_message.Message,), {
  'DESCRIPTOR' : _ALLTODOS,
  '__module__' : 'proto.todo_pb2'
  # @@protoc_insertion_point(class_scope:AllTodos)
  })
_sym_db.RegisterMessage(AllTodos)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'proto.todo_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)



_TODOAPP = _descriptor.ServiceDescriptor(
  name='TodoApp',
  full_name='TodoApp',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=167,
  serialized_end=395,
  methods=[
  _descriptor.MethodDescriptor(
    name='AddTodo',
    full_name='TodoApp.AddTodo',
    index=0,
    containing_service=None,
    input_type=_TODO,
    output_type=_EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ListAllTodos',
    full_name='TodoApp.ListAllTodos',
    index=1,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_ALLTODOS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='EditTodo',
    full_name='TodoApp.EditTodo',
    index=2,
    containing_service=None,
    input_type=_TODO,
    output_type=_EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RemoveTodo',
    full_name='TodoApp.RemoveTodo',
    index=3,
    containing_service=None,
    input_type=_TODO,
    output_type=_TODO,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateStatus',
    full_name='TodoApp.UpdateStatus',
    index=4,
    containing_service=None,
    input_type=_TODO,
    output_type=_TODO,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ListAllStream',
    full_name='TodoApp.ListAllStream',
    index=5,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_TODO,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetTodo',
    full_name='TodoApp.GetTodo',
    index=6,
    containing_service=None,
    input_type=_TODO,
    output_type=_TODO,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TODOAPP)

DESCRIPTOR.services_by_name['TodoApp'] = _TODOAPP

# @@protoc_insertion_point(module_scope)
