# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from proto import todo_pb2 as proto_dot_todo__pb2


class TodoStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.AddTask = channel.unary_unary(
        '/Todo/AddTask',
        request_serializer=proto_dot_todo__pb2.Task.SerializeToString,
        response_deserializer=proto_dot_todo__pb2.Empty.FromString,
        )
    self.ListAllTasks = channel.unary_unary(
        '/Todo/ListAllTasks',
        request_serializer=proto_dot_todo__pb2.Empty.SerializeToString,
        response_deserializer=proto_dot_todo__pb2.AllTasks.FromString,
        )
    self.EditTask = channel.unary_unary(
        '/Todo/EditTask',
        request_serializer=proto_dot_todo__pb2.Task.SerializeToString,
        response_deserializer=proto_dot_todo__pb2.Empty.FromString,
        )
    self.RemoveTask = channel.unary_unary(
        '/Todo/RemoveTask',
        request_serializer=proto_dot_todo__pb2.Task.SerializeToString,
        response_deserializer=proto_dot_todo__pb2.Task.FromString,
        )
    self.UpdateStatus = channel.unary_unary(
        '/Todo/UpdateStatus',
        request_serializer=proto_dot_todo__pb2.Task.SerializeToString,
        response_deserializer=proto_dot_todo__pb2.Task.FromString,
        )
    self.ListAllStream = channel.unary_stream(
        '/Todo/ListAllStream',
        request_serializer=proto_dot_todo__pb2.Empty.SerializeToString,
        response_deserializer=proto_dot_todo__pb2.Task.FromString,
        )
    self.GetTask = channel.unary_unary(
        '/Todo/GetTask',
        request_serializer=proto_dot_todo__pb2.Task.SerializeToString,
        response_deserializer=proto_dot_todo__pb2.Task.FromString,
        )


class TodoServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def AddTask(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListAllTasks(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def EditTask(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RemoveTask(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateStatus(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListAllStream(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetTask(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TodoServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'AddTask': grpc.unary_unary_rpc_method_handler(
          servicer.AddTask,
          request_deserializer=proto_dot_todo__pb2.Task.FromString,
          response_serializer=proto_dot_todo__pb2.Empty.SerializeToString,
      ),
      'ListAllTasks': grpc.unary_unary_rpc_method_handler(
          servicer.ListAllTasks,
          request_deserializer=proto_dot_todo__pb2.Empty.FromString,
          response_serializer=proto_dot_todo__pb2.AllTasks.SerializeToString,
      ),
      'EditTask': grpc.unary_unary_rpc_method_handler(
          servicer.EditTask,
          request_deserializer=proto_dot_todo__pb2.Task.FromString,
          response_serializer=proto_dot_todo__pb2.Empty.SerializeToString,
      ),
      'RemoveTask': grpc.unary_unary_rpc_method_handler(
          servicer.RemoveTask,
          request_deserializer=proto_dot_todo__pb2.Task.FromString,
          response_serializer=proto_dot_todo__pb2.Task.SerializeToString,
      ),
      'UpdateStatus': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateStatus,
          request_deserializer=proto_dot_todo__pb2.Task.FromString,
          response_serializer=proto_dot_todo__pb2.Task.SerializeToString,
      ),
      'ListAllStream': grpc.unary_stream_rpc_method_handler(
          servicer.ListAllStream,
          request_deserializer=proto_dot_todo__pb2.Empty.FromString,
          response_serializer=proto_dot_todo__pb2.Task.SerializeToString,
      ),
      'GetTask': grpc.unary_unary_rpc_method_handler(
          servicer.GetTask,
          request_deserializer=proto_dot_todo__pb2.Task.FromString,
          response_serializer=proto_dot_todo__pb2.Task.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Todo', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
