# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from proto import todo_pb2 as proto_dot_todo__pb2


class TodoAppStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.AddTodo = channel.unary_unary(
        '/TodoApp/AddTodo',
        request_serializer=proto_dot_todo__pb2.Todo.SerializeToString,
        response_deserializer=proto_dot_todo__pb2.Empty.FromString,
        )
    self.ListAllTodos = channel.unary_unary(
        '/TodoApp/ListAllTodos',
        request_serializer=proto_dot_todo__pb2.Empty.SerializeToString,
        response_deserializer=proto_dot_todo__pb2.AllTodos.FromString,
        )
    self.EditTodo = channel.unary_unary(
        '/TodoApp/EditTodo',
        request_serializer=proto_dot_todo__pb2.Todo.SerializeToString,
        response_deserializer=proto_dot_todo__pb2.Empty.FromString,
        )
    self.RemoveTodo = channel.unary_unary(
        '/TodoApp/RemoveTodo',
        request_serializer=proto_dot_todo__pb2.Todo.SerializeToString,
        response_deserializer=proto_dot_todo__pb2.Todo.FromString,
        )
    self.UpdateStatus = channel.unary_unary(
        '/TodoApp/UpdateStatus',
        request_serializer=proto_dot_todo__pb2.Todo.SerializeToString,
        response_deserializer=proto_dot_todo__pb2.Todo.FromString,
        )
    self.ListAllStream = channel.unary_stream(
        '/TodoApp/ListAllStream',
        request_serializer=proto_dot_todo__pb2.Empty.SerializeToString,
        response_deserializer=proto_dot_todo__pb2.Todo.FromString,
        )
    self.GetTodo = channel.unary_unary(
        '/TodoApp/GetTodo',
        request_serializer=proto_dot_todo__pb2.Todo.SerializeToString,
        response_deserializer=proto_dot_todo__pb2.Todo.FromString,
        )


class TodoAppServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def AddTodo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListAllTodos(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def EditTodo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RemoveTodo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateStatus(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListAllStream(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetTodo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TodoAppServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'AddTodo': grpc.unary_unary_rpc_method_handler(
          servicer.AddTodo,
          request_deserializer=proto_dot_todo__pb2.Todo.FromString,
          response_serializer=proto_dot_todo__pb2.Empty.SerializeToString,
      ),
      'ListAllTodos': grpc.unary_unary_rpc_method_handler(
          servicer.ListAllTodos,
          request_deserializer=proto_dot_todo__pb2.Empty.FromString,
          response_serializer=proto_dot_todo__pb2.AllTodos.SerializeToString,
      ),
      'EditTodo': grpc.unary_unary_rpc_method_handler(
          servicer.EditTodo,
          request_deserializer=proto_dot_todo__pb2.Todo.FromString,
          response_serializer=proto_dot_todo__pb2.Empty.SerializeToString,
      ),
      'RemoveTodo': grpc.unary_unary_rpc_method_handler(
          servicer.RemoveTodo,
          request_deserializer=proto_dot_todo__pb2.Todo.FromString,
          response_serializer=proto_dot_todo__pb2.Todo.SerializeToString,
      ),
      'UpdateStatus': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateStatus,
          request_deserializer=proto_dot_todo__pb2.Todo.FromString,
          response_serializer=proto_dot_todo__pb2.Todo.SerializeToString,
      ),
      'ListAllStream': grpc.unary_stream_rpc_method_handler(
          servicer.ListAllStream,
          request_deserializer=proto_dot_todo__pb2.Empty.FromString,
          response_serializer=proto_dot_todo__pb2.Todo.SerializeToString,
      ),
      'GetTodo': grpc.unary_unary_rpc_method_handler(
          servicer.GetTodo,
          request_deserializer=proto_dot_todo__pb2.Todo.FromString,
          response_serializer=proto_dot_todo__pb2.Todo.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'TodoApp', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
